data_science/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # Django auth
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

data_science/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('data_science.apps.public.urls')),
    path("accounts/", include('data_science.apps.accounts.urls')),
]

data_science/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):

    # user
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    # settings
    is_full_name_displayed = models.BooleanField(default=True)

    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
    interests = models.ManyToManyField(UserInterest, blank=True)

data_science/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

data_science/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

data_science/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <!-- About Section-->
    <section class="page-section mb-0" id="about">
        <div class="container">
            <!-- About Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase">About</h2>
            <!-- About Section Content-->
            <div>
                <blockquote><em>
                    The truth is a fog, in which one person sees a heavenly host and the other one sees a flying
                    elephant. ~ Dodger
                </em></blockquote>
                <p>You would think that, now that all of us have access to so much information, getting to the truth
                    would be relatively easy. Uh!
                </p>
                <p>Even if everybody gains enough knowledge on statistics and critical thinking (ie uses
                    scientific methods and makes evidence-based decisions), there is no guarantee this would lead
                    to truth, and to "right" decisions. And scientists are not exempt from motivated reasoning.
                    Scientists are human and have biases, just like everyone else. Men have not wanted to research
                    sexe-related differences for decades, other than those that confirm their beliefs on women. Not
                    until women started researching some idiotic claims, were such "truths" proven wrong.
                    Bias in science is fairly common, even more now with the interrelated interests of the health
                    industry, the medical world, and science journalists.
                </p>
                <p>Most scientists are honorable and really do have the best interests of the public at heart, but a
                    few will sell their souls for money and power.
                </p>
                <p>
                    In this digital day and age, in which data scientists prepare data for executives to base their
                    decisions on, we need to be doubly alert, and become data scientists ourselves. We need to not only
                    develop our own data analyses and predictions, we will also need to study bias in how we develop our
                    analyses and predictions, and we need to study our own personal biases, deeply. This site is
                    dedicated to that.
                </p>
            </div>
        </div>
    </section>
{% endblock %}

data_science/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Data Science Projects{% endblock %}

{% block content %}
    <!-- Login Section-->
    <section class="page-section mb-0" id="profile">
        <div class="container align-items-center">
            <!-- Login Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase">Login</h2>
            <br/>
            <!-- Login Section Content-->
            <div class="text-center">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Login</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

data_science/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}
    <!-- Profile Section-->
    <section class="page-section mb-0" id="profile">
        <div class="container align-items-center">
            <!-- Profile Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase">Profile</h2>

            <!-- Profile Section Content-->
            {% with profile=user.profile %}
               <div class="profile">
                    <div class="name text-center">
                        <p>{{ user.get_full_name }} (@{{user.username}})</p>
                        {% if profile %}
                            <p>{{ profile.persona|default:"" }}</p>
                            {% if profile.linkedin_url %}
                            <a href="{{ profile.linkedin_url }}" class="btn btn-just-icon btn-link"><i class="fab fa-linkedin-in"></i></a>
                            {% endif %}
                            {% if profile.twitter_url %}
                            <a href="{{ profile.twitter_url }}" class="btn btn-just-icon btn-link"><i class="fab fa-twitter"></i></a>
                            {% endif %}
                            {% if profile.youtube_url %}
                            <a href="{{ profile.youtube_url }}" class="btn btn-just-icon btn-link"><i class="fab fa-youtube"></i></a>
                            {% endif %}
                        {% endif %}
                    </div>
               </div>

                {% if profile %}
                <div class="description text-center">
                    {% with website=profile.website|default:"" %}
                        <a href="{{website}}">{{ website }}</a>
                    {% endwith %}
                </div>
                <div class="description text-center">
                    Interests:
                    {% for interest in profile.interests.all %}
                        <span>
                            {{ interest.name }}{% if not forloop.last %}, {% endif %}
                        </span>
                    {% endfor %}
                </div>
                <div class="description text-center">
                    <p>{{ profile.bio|default:"" }}</p>
                </div>
                {% endif %}
                <br/>
            {% endwith %}
        </div>
    </section>
{% endblock %}

data_science/templates/base.html
{% load static %}

<!-- templates/base.html-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="DS Projects" />
    <meta name="author" content="Ty Myrddin" />

    <title>{% block title %}Dodger{% endblock %}</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'theme/assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="{% static 'fonts/awesome/js/all.js' %}"></script>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />
    <!-- CSS overwrites-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
</head>
<body>
{% include 'navbar.html' %}

    <!-- Main-->
    <main id="main">
        <!-- child template -->
        {% block content %}
        {% endblock %}
    </main>

    <!-- Footer-->
    <footer class="footer text-center">
        <div class="container">
            <p><a href="https://tymyrddin.space/">Ty Myrddin</a> (2022)</p>
        </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="{% static 'theme/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core theme JS-->
    <<script src="{% static 'theme/js/scripts.js' %}"></script>
</body>
</html>

data_science/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
    <!-- Masthead-->
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Avatar Image-->
            <img class="masthead-avatar mb-5" src="{% static 'img/dodger.png' %}" alt="Tophat logo" />
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0">truth is a fog</h1>
        </div>
    </header>
{% endblock %}

data_science/templates/navbar.html
<!-- Navigation-->

{% url 'public:index' as index_url %}
{% url 'public:about' as about_url %}
{% url 'accounts:profile' as profile_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}

<nav class="navbar navbar-expand-lg hs-bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ index_url }}">Dodger DS</a>
        <button class="navbar-toggler text-uppercase font-weight-bold hs-bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3" href="">Projects</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == profile_url %}active{% endif %}" href="{{ profile_url }}">Profile</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == logout_url %}active{% endif %}" href="{{ logout_url }}">Logout</a></li>
                {% else %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == login_url %}active{% endif %}" href="{{ login_url }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!--<nav>-->
<!--    <ul>-->
<!--        {% url 'public:index' as index_url %}-->
<!--        <li class="nav__item">-->
<!--            {% if request.path == index_url %}Home{% else %}-->
<!--            <a href="{{ index_url }}" class="nav__link">Home</a>{% endif %}-->
<!--        </li>-->
<!--        <li class="nav__item"><a href="" class="nav__link">Projects</a>-->
<!--        </li>-->
<!--        {% url 'public:about' as about_url %}-->
<!--        <li class="nav__item">{% if request.path == about_url %}About{% else %}-->
<!--            <a href="{{ about_url }}" class="nav__link">About</a>{% endif %}-->
<!--        </li>-->
<!--        <span style="float:right">-->
<!--            <li class="nav__item">-->
<!--                {% if user.is_authenticated %}-->
<!--                    {% url 'accounts:profile' as profile_url %}-->
<!--                    {% if request.path == profile_url %}{{ user.username }}{% else %}-->
<!--                    <a href="{{ profile_url }}" class="nav__link">{{ user.username }}</a>-->
<!--                    {% endif %}-->
<!--                {% endif %}-->
<!--            </li>-->
<!--            <li class="nav__item">-->
<!--                {% if user.is_authenticated %}-->
<!--                <span><a href="{% url 'accounts:logout' %}">Logout</a></span>-->
<!--                {% else %}-->
<!--                <span class="nav__item"><a href="{% url 'accounts:login' %}">Login</a></span>-->
<!--                {% endif %}-->
<!--            </li>-->
<!--        </span>-->
<!--    </ul>-->
<!--</nav>-->